### ISSUE TITLE
Dockerfile does not install libzmq to support latest zmq additions

### ISSUE THREAD

**Issue by geminoz** [crholliday/iota-prom-exporter#11]
First of all, thanks for the IOTA prometheus exporter, great stuff.

As per subject above, the recent zmq additions require libzmq to be installed on the hosting system. Using the Dockerfile provided the node process segfaults at execution, due to missing zmq libraries.

At this stage, despite some tests, I did not manage to have alpine work with zmq: installing the library is easy `apk add --no-cache libzmq` but Alpine does not have a typical ldconfig structure. I will investigate further on how to get Alpine to load the new library so that node wouldn't segfault.

In the meantime the latest master works with a Dockerfile with:
`FROM node:9-stretch

RUN apt-get update && apt-get install -y libzmq5`

**Comment by crholliday** [comment]
@bambash please see above...

**Comment by bambash** [comment]
I'll check this out tonight

**Comment by crholliday** [comment]
#13 should fix.. thanks @bambash
