### ISSUE TITLE
Please allow disabling market price metrics

### ISSUE THREAD

**Issue by geminoz** [crholliday/iota-prom-exporter#12]
At present I am commenting out in app.js the following line:

`const marketInfoSocket = require('./marketInfoSocketRC')(trades)`

However please consider adding a configuration option to selectively enable/disable metric groups (particularly market info). 

Thank you

**Comment by crholliday** [comment]
I'll add this... thanks.

**Comment by crholliday** [comment]
This has been added and is on master
